### ISSUE TITLE
TRUST4 and exome sequencing data

### ISSUE THREAD

**Issue by benostendorf** [liulab-dfci/TRUST4#14]
Can TRUST4 be used to infer T cell infiltration from whole exome sequencing data (i.e., quantify the fraction of recombined VDJ regions)?

Thank you!

**Comment by mourisl** [comment]
Theoretically, TRUST4 could reconstruct the CDR3s from the WES data. Maybe this could be used to compare the infiltration between two samples by looking at how many reads covering CDR3 ideally. But I don't think it can be used to quantify the recombined T cell, since many of the reads covering V or J gene may not overlap CDR3 region and may need some sophisticated adjustment.
