### ISSUE TITLE
The performance on 3' scRNAseq 

### ISSUE THREAD

**Issue by cissizhang** [liulab-dfci/TRUST4#153]
Hi, I used TRSUT4 on 3' scRNAseq data. However, less than 10% of the TCRs were covered and reported in the results. I have 30K cells identified in 10X genomes cellranger and filtered by Seurat. TRUST4 reported 2300 cells (the input file is a bam file generated by cellranger). Is this expected? Any explanation will be appreciated. Thank you.

**Comment by mourisl** [comment]
The sensitivity on 3' scRNAseq is expected to be low. This is because the VDJ region is on the 5' end of the mRNA, and the constant gene sequence is pretty long (can be a few thousand bases). But still, if there is an expanded clonotype, it is still more likely to be captured than other clonotypes by chance.

**Comment by cissizhang** [comment]
Thanks for your reply and clear explanation.
