### ISSUE TITLE
Creating a custom annotation gtf file

### ISSUE THREAD

**Issue by guillemsanchezsanchez1996** [liulab-dfci/TRUST4#179]
Hello,

I discovered recently your package and I would like to give it a try with some scRNAseq data that I have from naked mole rat samples. I was wondering which would be your suggested approach to create a custom gtf file. In the genome used to generate the original bam file there is no TCR gene annotation but recently IMGT has released their own annotation. I was wondering what shall I do to create this custom gtf file if in the original genome there is no tcr annotation.

Thanks in advance,

Guillem

**Comment by mourisl** [comment]
You will need the rat reference genome, the GTF file containing the annotation for the TCR and BCR genes, and a file listing the TCR and BCR V, D, J, C gene names (one name per line).

Then you can run the script "perl BuildDatabaseFa.pl reference.fa annotation.gtf gene_name.list > TCR_BCR_coord.fa", which will create a file containing the TCR/BCR V,D,J,C sequences extracted from the reference genome and their genome coordinate in the fasta header.  The TCR_BCR_coord.fa file will be used for the "-f" option in TRUST4. 

Since your current GTF file does not contain the TCR genes, I think one way to do is to use RNA-seq data to identify the genes, with methods like PsiCLASS, StringTie, Cufflinks or Scallop. Then you can cross-reference the gene sequence with human or mouse to identify their potential gene names.

Another approach is to start from the fastq file, where you can directly use the IMGT sequences as reference.

**Comment by ReyesMurrieta-Zoetis** [comment]
Hi, for cases like this where we have non-model references would it be possible to use gene_id instead of gene_name from the reference files to create the TCR_BCR_coord.fa? As in most of these cases gene_name have not been associated with coding loci for non-model organism when cross-referenced against human or mouse?

**Comment by mourisl** [comment]
TRUST4 needs the prefix like "TRBV", "IGHJ" to identify the V,D,J roles. So if you can prepend such name prefixes to the gene_id, it should be fine.

If you have the IMGT-like reference file for the --ref option and only need the gene coordinates to find the candidate VDJC reads, I just added the option "--assembleWithRef" option to the github repo that could be useful for you. With this option, you don't need to worry about the prefix of the gene names.

**Comment by guillemsanchezsanchez1996** [comment]
Hello thanks for the answer,

Is it possible to use the fasta provided by IMGT (https://www.imgt.org/ligmdb/view.action?format=FASTA&id=IMGT000070) to create an "artificial genome" and use the coordinates from it to create the gtf file?

Guillem

**Comment by mourisl** [comment]
That depends on how the alignment was conducted to generate the BAM file. Is the contigs/chromosome name something like "RPGA01000024.1" or "contig23"? 

If you know the coordinate for the entries, you don't need to create the gtf file. You can directly create a fasta from the current file. In each header, you shall put the "chrom_name start end strand" information in the header field. The format in "hg38_bcrtcr.fa" is a good example.

**Comment by guillemsanchezsanchez1996** [comment]
Hi,

Thanks for the suggestion. For the moment I succed to extract CDR3 sequences using theraw fastq. I will still try to go for the bam approach once I have more time. Shall I close the issue?

Thanks again for this amazing package.
Guillem

**Comment by mourisl** [comment]
Glad TRUST4 works on your fastq file. You can close the issue for now. I'm thinking about streamlining the process on non-model species, and hope I can implement it in near future.
