### ISSUE TITLE
Annotator error

### ISSUE THREAD

**Issue by WuRAFY** [liulab-dfci/TRUST4#322]
Firstly thanks for the great tool! When I ran TRUST4 on bam file of 10x scRNA-seq, some errors happened in only part of samples. And Rerun did not solve the error. I installed TRUST4 form github. This is the error report

```
[Wed Oct 23 15:31:29 2024] TRUST4 v1.1.5-r556 begins.
[Wed Oct 23 15:31:29 2024] SYSTEM CALL: /home/wufy/software/trust4/TRUST4/annotator -f /home/wufy/software/trust4/TRUST4/hg38_bcrtcr.fa -a LUAD_RM02_01_final.out -t 1 -o LUAD_RM02_01 --notIMGT  --barcode -r LUAD_RM02_01_assembled_reads.fa --airrAlignment > LUAD_RM02_01_annot.fa
[Wed Oct 23 15:31:29 2024] Start to annotate assemblies.
sh: 行 1: 331782 段错误               (吐核)/home/wufy/software/trust4/TRUST4/annotator -f /home/wufy/software/trust4/TRUST4/hg38_bcrtcr.fa -a LUAD_RM02_01_final.out -t 1 -o LUAD_RM02_01 --notIMGT --barcode -r LUAD_RM02_01_assembled_reads.fa --airrAlignment > LUAD_RM02_01_annot.fa
system /home/wufy/software/trust4/TRUST4/annotator -f /home/wufy/software/trust4/TRUST4/hg38_bcrtcr.fa -a LUAD_RM02_01_final.out -t 1 -o LUAD_RM02_01 --notIMGT  --barcode -r LUAD_RM02_01_assembled_reads.fa --airrAlignment > LUAD_RM02_01_annot.fa failed: 35584 at /home/wufy/software/trust4/TRUST4/run-trust4 line 60.
```

Much thanks 
FY

**Comment by mourisl** [comment]
Could you please share the LUAD_RM02_01_final.out file? This could be a bug.

**Comment by WuRAFY** [comment]
https://1drv.ms/u/c/1aa2c7aee02dd080/EUEAaRy9kFpLjtheB1OupfYBMcKNS40HxqptRv_re3Yh0g?e=NtRAwz

This is the file

**Comment by mourisl** [comment]
If it is feasible, could you please share the toassemble_1/_2/_bc files with me? I'll look into this issue. Thanks!

**Comment by WuRAFY** [comment]
https://1drv.ms/u/c/1aa2c7aee02dd080/EUAk7Jb3SSROs7wBYeSoQ64B_7gFKUXTGOu5JA0jp8_iMA?e=qhhu5d

This is the toassemble_bc file. No toassemble_1/_2 files generated.

**Comment by WuRAFY** [comment]
v1.1.4 works fine. Much thanks! If you need more files, please let me know

> It seems the >ACGATGTGTGACGCCT-1_8494 contig is empty in the final.out file. This could be a bug in recent code, and might take some time to debug. You may test whether TRUST4 v1.1.4 from the release page or bioconda works on your sample. Thanks.

**Comment by mourisl** [comment]
I guess your data might be single-end for the sequencing part then. Do you have the "toassemble.fq" file? Thank you!

**Comment by WuRAFY** [comment]
https://1drv.ms/u/c/1aa2c7aee02dd080/EQawvSNtcJhKpI2yFnhF1LQB0yZQTiB9bMoyb9fcNTMqoQ?e=7E6Ajn
These are the files generated by TRUST4

> I guess your data might be single-end for the sequencing part then. Do you have the "toassemble.fq" file? Thank you!

**Comment by mourisl** [comment]
Thank you for sharing the file. Based on the data, I have reproduced the error and fixed the bug. The error happens to some reads with too many Ns, and the main assembly program may make them empty strings and use in the assembly causing some empty contig in the output. I have pushed the code to the master branch, could you please give it a try? Thank you!

**Comment by WuRAFY** [comment]
Now no errors reported by TRUST4. But I still have few questions (I am new to TCR/BCR analysis, sorry for the questions may be silly to you :) )
1. Do I need to rerun TRUST4 for samples which results have been successfully generated by TRUST4 v1.1.4?
2. Is it normal that only a part of B cells and T cells have TCR and BCR records in TRUST4 results?
3. What is the meaning of *_report.tsv for scRNA-seq data? the sum of counts in this file is larger than number of records in *_barcode_report.tsv.
4. If I want to calculate the percentage of expanded T/B cells (clone size >1 in some articles) in a sample, could you please give some suggestions based on TRUST4 results or other recommended anaylsis pipeline?

Much Thanks!

**Comment by mourisl** [comment]
Thank you for testing!

> Do I need to rerun TRUST4 for samples which results have been successfully generated by TRUST4 v1.1.4 after this fix?
Is it normal that only a part of B cells and T cells have TCR and BCR records in TRUST4 results?

It's more important to use a consistent version of software to analyze your data. Since TRUST4 v1.1.4 is a formal release, you can use that version. The formal v1.1.5 probably will take some time to release, I still need to fix several other parts. It is normal that only part of T and B cells can have TCR,BCR results. I guess your data is not VDJ amplified, so the each cell will have few number of reads from the receptor region and the sensitivity is not super high.

> What is the meaning of *_report.tsv for scRNA-seq data? the sum of counts in this file is larger than number of records in *_barcode_report.tsv.

The report is aggregated count for each chain's clonotypes (V,J,C and CDR3). Each row in the barcode_report file is for a cell, so there can be two items/chains for each record so the report can be longer than the barcde_report file. In single-cell analysis, I would suggest use the barcode_report/barcode_airr file. You can use it to overlay the barcodes passed the Seurat/Scanpy-qc and the results will be better.

> If I want to calculate the percentage of expanded T/B clones (clone size >1 mentioned in some articles) in a sample, could you please give some suggestions based on TRUST4 results or other recommended anaylsis pipeline?

You can either use your own script that the cells with the same TRB/IGH CDR3 as the clonotype, or use packages like scRepertoire or scirpy for that.

**Comment by WuRAFY** [comment]
Thanks for suggestions!
