### ISSUE TITLE
free(): invalid next size (normal)

### ISSUE THREAD

**Issue by Nottooxabi** [liulab-dfci/TRUST4#42]
Hello again, 

As per my previous discussion post I re-tried to analyse some enriched TCR sequences. This time I tested without or without the --repseq option (It's very slow without the repseq option, but it processed ~800000 more reads?). In both cases the software encountered an error in the compute cdr3 abundance step. Again not sure if theres a compiling fault on our end or not.

I've attached the outout files below.

cheers,
Tony
  
[test_hpc.txt](https://github.com/liulab-dfci/TRUST4/files/6512183/test_hpc.txt)

**Comment by mourisl** [comment]
From my experience, some TCR-seq/BCR-seq may have some primer sequences or other noise sequences. This will cause many spurious contigs and significantly slows the program down. --repseq option will drastically trim the read ends, so many of the reads could be filtered due to this. I want to mention that TRUST4 was not designed for TCR/BCR enriched data, so the results might not be optimal.

I will check why the program crashed in the abundance estimation step. Is it possible for you to share the files output1/_assembled_reads.fa and output1/_final.out with us? Thank you.

**Comment by Nottooxabi** [comment]
Hey,

Thanks for the quick reply. Files were too big for me to attach to here, I've just emailed them to you.

**Comment by mourisl** [comment]
Thanks for sharing the data! I just fixed a possible bug with your provided data. Could you pull the repo and give it a try? You can run TRUST4 with the option "--stage 2", so it will restart from the annotation stage. Thank you.
