### ISSUE TITLE
Slow program Speed

### ISSUE THREAD

**Issue by antgomo** [liulab-dfci/TRUST4#43]
HI,

i am using TRUST4 to improve my results on paired-end RNAseq. Previously, I used MIXCR on my FASTQs for same sample on 2 computational nodes and I obtained results after 5 hours.  Using TRUST4 on 2 nodes for same sample the program is still running after 48 hours!
As far as I remember, you said in the paper that your method is faster that MIXCR, Am i missing something?

Kind Regards

By the way, this is my command line

run-trust4 -t 2 -1 /5632-RMM-0015_S15_L001.final_R1.fq.gz -2 5632-RMM-0015_S15_L001.final_R2.fq.gz -f ~/soft/TRUST4/hg19_bcrtcr.fa --ref ~/soft/TRUST4/IMGT+C.fa

**Comment by mourisl** [comment]
Could you please show me the running log from TRUST4 (the output on the screen)? Thank you.

**Comment by antgomo** [comment]
Hi, i am using screen so i can put you the last lines

Wed May 19 07:14:11 2021] Processed 4100000 reads (3724879 are used for assembly).
[Wed May 19 07:33:55 2021] Processed 4200000 reads (3806399 are used for assembly).
[Wed May 19 07:52:20 2021] Processed 4300000 reads (3887235 are used for assembly).
[Wed May 19 08:12:38 2021] Processed 4400000 reads (3968941 are used for assembly).
[Wed May 19 08:33:17 2021] Processed 4500000 reads (4041015 are used for assembly).
[Wed May 19 09:34:22 2021] Processed 4600000 reads (4117866 are used for assembly).
[Wed May 19 10:34:00 2021] Processed 4700000 reads (4208589 are used for assembly).
[Wed May 19 11:14:53 2021] Processed 4800000 reads (4291259 are used for assembly).
[Wed May 19 11:42:50 2021] Processed 4900000 reads (4360815 are used for assembly).
[Wed May 19 12:03:12 2021] Processed 5000000 reads (4417417 are used for assembly).
[Wed May 19 12:26:51 2021] Processed 5100000 reads (4448615 are used for assembly).
[Wed May 19 12:28:54 2021] Processed 5200000 reads (4470846 are used for assembly).
[Wed May 19 12:32:35 2021] Assembled 4478660 reads.
[Wed May 19 12:32:35 2021] Try to rescue 310039 reads for assembly.
[Wed May 19 14:08:20 2021] Rescued 81349 reads.
[Thu May 20 03:39:10 2021] Extend assemblies by mate pair information.
[Thu May 20 04:07:39 2021] Remove redundant assemblies.
[Thu May 20 04:39:52 2021] Finish assembly.
[Thu May 20 04:42:31 2021] SYSTEM CALL: /home/tonig/soft/TRUST4/annotator -f /home/tonig/soft/TRUST4/IMGT+C.fa -a TRUST_5632-RMM-0015_S15_L001_final.out -t 2 -o TRUST_5632-RMM-0015_S15_L001  -r TRUST_5632-RMM-0015_S15_L001_assembled_reads.fa > TRUST_5632-RMM-0015_S15_L001_annot.fa
[Thu May 20 04:42:32 2021] Start to annotate assemblies.
[Thu May 20 05:07:03 2021] Start to realign reads for CDR3 analysis.

**Comment by mourisl** [comment]
TRUST4 should be able to handle 5M candidate reads. One interesting thing is that because more and more contigs need to be considered during assembly, the processing time for every 100K time should be increasing. Though in your case the processing time between 4.6M and 4.7M is very long, and it gradually decreased to 2 minutes between 5.1M and 5.2M case. The step before "extend assemblies by mate pair information" feels also too slow, which took 13.5 hours. Can you count how many lines are in the file TRUST_5632-RMM-0015_S15_L001_final.out? Thank you!

**Comment by antgomo** [comment]
Hi Li,

thanks for the fast reply,

here is the count

3749760 TRUST_5632-RMM-0015_S15_L001_final.out

**Comment by mourisl** [comment]
The number of assembled sequences is indeed very high. This is either due to the heterogeneity in your sample, or there is much noise in the data. What is the read length for your sample? 

One unlikely reason is that hg19_bcrtcr.fa may not be ideal for your data. Can you try the command : 
"run-trust4 -t 2 -1 5632-RMM-0015_S15_L001.final_R1.fq.gz -2 5632-RMM-0015_S15_L001.final_R2.fq.gz -f ~/soft/TRUST4/hg38_bcrtcr.fa --ref ~/soft/TRUST4/IMGT+C.fa" . This is not likely to be the reason, if you found TRUST4 is still too slow, you can kill this test. Thank you.

**Comment by antgomo** [comment]
must be hg19, this is the genome version that we used to align the samples

may the point is this

    perl BuildImgtAnnot.pl Homo_sapiens > IMGT+C.fa

I used this command to generate the IMGT+C.fa file. This is calling hg38 (http://www.imgt.org/download/GENE-DB/) ?? hence my data is in hg19 and probably this is the slow thing?

**Comment by mourisl** [comment]
You are running TRUST4 on the fastq files, so it should not be affected by the genome version. What matters is the V,J,C sequences for hg38 and hg19 might be a bit different and TRUST4 may extract some irrelevant sequences, which may slow the program down. The hg19 and hg38 V,J,C sequences are very similar though, so it is unlikely to be the reason for the slow speed.

**Comment by antgomo** [comment]
Well let me test your approach and i'll be back and tell you

Thanks!

**Comment by mourisl** [comment]
Thank you! One more question, what is the read length for your sample?

**Comment by antgomo** [comment]
paired-end 100bps per pair, total 200bps

**Comment by mourisl** [comment]
One thing just comes to my mind is that could you please show me the running time for "Read in and count kmers for 100000 reads. ..." in the new run if it is available? The computation for those steps is very straightforward, and should only take about 2 or 3 seconds to finish per 100K reads. This is a good place to check whether the system is slow.

**Comment by antgomo** [comment]
[Thu May 20 19:59:56 2021] Read in and count kmers for 100000 reads.
[Thu May 20 20:00:03 2021] Read in and count kmers for 200000 reads.
[Thu May 20 20:00:11 2021] Read in and count kmers for 300000 reads.
[Thu May 20 20:00:36 2021] Found 293179 reads.
[Thu May 20 20:00:41 2021] Finish sorting the reads.
[Thu May 20 20:00:58 2021] Finish rough annotations.
[Thu May 20 20:02:22 2021] Processed 100000 reads (73706 are used for assembly).

**Comment by antgomo** [comment]
I think we rang the bell.. didn't we?

**Comment by mourisl** [comment]
Is this from the same data using hg38? The difference is huge! I think I need to check the hg19 annotation file.

**Comment by antgomo** [comment]
Yes, is from hg38_bcrtcr.fa using same data

**Comment by antgomo** [comment]
Finished in less than 5 minutes with only 2 cores, thanks for the help!

So i will remove your hg19_bcrtcr.fa and i will use hg38 for all my samples, thanks again!

**Comment by mourisl** [comment]
Thank you for the updates! In the hg38 version, it found much fewer candidate reads than before, so I'm wondering how does it compare with your original MiXCR results.

There could be some other slow samples even with hg38. One thing I notice is that the "count kmer" steps are relatively slow on your system. Are you running it on a local computer or on a server? For example, in the logs here: #29 , all of our results were about 2 seconds per 100K reads.

**Comment by antgomo** [comment]
Well, i could send you the result of this particular comparison regarding MIXCR, tomorrow the postdoc in charge will take a look and i will send to you

Respect to the program running, i am running it on a server, so i don't know what is the particular problem i will launch a set of samples tonight and see if tomorrow are finished

**Comment by antgomo** [comment]
one final question, how can i re-direct the output of the program to a particular folder? 
With this simple command?

~/soft/TRUST4/./run-trust4 -t 2 -1 /home/DATA/RNASeq/Proj6Celgene/COMB_FASTQ/5632-RMM-0015_S15_L001.final_R1.fq.gz -2 /home/DATA/RNASeq/Proj6Celgene/COMB_FASTQ/5632-RMM-0015_S15_L001.final_R2.fq.gz -f ~/soft/TRUST4/hg38_bcrtcr.fa --ref ~/soft/TRUST4/IMGT+C.fa > my.ouput_folder/

**Comment by mourisl** [comment]
The option "--od" will specify the output directory, "-o" can specify the output prefix (otherwise it will automatically decide it based on file name.) So you can run TRUST4 with:

~/soft/TRUST4/./run-trust4 -t 2 -1 /home/DATA/RNASeq/Proj6Celgene/COMB_FASTQ/5632-RMM-0015_S15_L001.final_R1.fq.gz -2 /home/DATA/RNASeq/Proj6Celgene/COMB_FASTQ/5632-RMM-0015_S15_L001.final_R2.fq.gz -f ~/soft/TRUST4/hg38_bcrtcr.fa --ref ~/soft/TRUST4/IMGT+C.fa --od my.output_folder

**Comment by antgomo** [comment]
MAny thanks!

**Comment by mourisl** [comment]
I just reproduced the slow issue using hg19_bcrtcr.fa on FASTQ file on our data. I think it might due to that the gencode annotation for hg19 was produced by lifting hg38 version over and could cause some weird issue. Also the current hg19_bcrtcr.fa contains some D genes which might also cause issue when extracting candidate reads. I just updated the hg19_bcrtcr.fa file with gencode.v19, which was produced on hg19, and the speed issue seems got resolved and obtained similar results when using hg38_bcrtcr.fa.
