### ISSUE TITLE
Identify Reads associated with different CloneIds 

### ISSUE THREAD

**Issue by jkbenotmane** [liulab-dfci/TRUST4#57]
Is the "cid" column in report.tsv the same as in the the assign.out file? 
Because if so this would mean the every clone is just backed by one read.
Do I misunderstand the output?

**Comment by mourisl** [comment]
Since your data set is long read, each read probably is a full-length transcript already. They have sequencing errors (I assume) or UTR regions that make them unable to be merged into one contig. Therefore, it is likely that each read corresponds to one contig in your case.

I think for the long transcriptome read like Nanopore, it does not make much sense for the de novo assembly. Instead, directly annotation each read to get CDR3 information and other regions might be more appropriate.

**Comment by jkbenotmane** [comment]
Thank you very much for the good Input, we will definetly think about it. 
Even though a question still remains as I don´t understand how I then can compute Clones with different, distinct Counts from my Data if when using the cid Column I can only match one contig from the assign.out file.
Is the cid Really the same as the one in the report.tsv?
