### ISSUE TITLE
10X data processing chemistry

### ISSUE THREAD

**Issue by tAndreani** [liulab-dfci/TRUST4#7]
Hello,  

I am wondering if in the single-cell modiality, TRUST4 can handle normal single-cell RNA-seq of 10X chemistry or whether it is intended only for the V(D)J chemistry protocol of 10X.  

Thank you in advance for any reply.
Best

**Comment by mourisl** [comment]
By normal, do you mean 10X 3' data? Because in 3' data, there is little coverage on the CDR3 region, TRUST4 performs much better on the 5' data from 10X. There is no need for the bcr/tcr amplification part, just the gene expression protocol is sufficient.

**Comment by tAndreani** [comment]
thank you for the reply, did you make a small benchmark for this? or is there any paper where to read this? I have read the Nat Gen papers where they explain the development of TRUST for T-cell and B-cell.. Thanks in advance for any reply.

**Comment by mourisl** [comment]
We are finishing up the manuscript for TRUST4 (that's why we only released the executable files now). By benchmark, which part do you need?

**Comment by tAndreani** [comment]
across technology performance like 10X 3' or 10X 5' or 10X V(D)J or SMART-seq2 for example...

**Comment by mourisl** [comment]
We are finishing up the manuscript for TRUST4 (that's why we only released the executable files now). By benchmark, in 3' data, only a handful of B cell and T cell could find CDR3s. For 5' data, TRUST4's results agreed with corresponding cellranger VDJ very well, though slightly less cells were with paired-chains. This is because TRUST4 uses unamplified data, and we expect the sensitivity to be lower than the V(D)J amplified data.

**Comment by mourisl** [comment]
For SMART-seq, since the data is already cell by cell, we regard each cell as a bulk data, and then pick the most abundant chains as representative. The results were quite good, agrees with other SMART-seq-based BCR/TCR assemblers, on both CDR3 sequence and full-length sequence.
