### ISSUE TITLE
Big difference between TRUST4 TCR result and cellranger  TCR result   

### ISSUE THREAD

**Issue by maqueredkop** [liulab-dfci/TRUST4#82]
Hello, recently I test the TRUST4, the test data is 10X VDJ dataset from the link: [https://www.10xgenomics.com/resources/datasets/pbm-cs-of-a-healthy-donor-tcr-enrichment-from-amplified-c-dna-1-standard-3-0-0](https://www.10xgenomics.com/resources/datasets/pbm-cs-of-a-healthy-donor-tcr-enrichment-from-amplified-c-dna-1-standard-3-0-0)
And the TRUST4 command is below:

`trust4  
    -u ./vdj_v1_hs_pbmc2_t_fastqs/vdj_v1_hs_pbmc2_t_S1_L00*_R2_*.fastq.gz  
    --barcode ./vdj_v1_hs_pbmc2_t_fastqs/vdj_v1_hs_pbmc2_t_S1_L00*_R1_*.fastq.gz  
    --barcodeRange 0 15 + 
    --barcodeWhitelist $barcode_whitelist 
    --UMI ./vdj_v1_hs_pbmc2_t_fastqs/vdj_v1_hs_pbmc2_t_S1_L00*_R1_*.fastq.gz 
    --umiRange 16 25 + 
    --repseq 
    -t 10 
    -f hg38_bcrtcr.fa  
    --ref  human_IMGT+C.fa  
    -o TCR 
    --od ./TCR_trust4_result/ `

So I compared the cellranger TCR result with the TRUST4 TCR result, and found that the T cell number identified (barcode count) in barcode_report.tsv from TRUST4  is more than 20k, but the T cell number from cellranger is only about 3000 (which was validated by CD3+ fraction in antibody data ). So the latter result number  is more accurate, technically. 
Now my question is: Why are there so many T cell identified in TRUST4 result, which mostly are likely to be false postive ? 

Thank you!

**Comment by mourisl** [comment]
Since this is from TCR amplified data, I think CellRanger may filter the cells with too few reads supporting the TCR sequence. You can filter the low abundance or cells with only one chain in TRUSt4 for that. 

Another reason could be the diffusion of mRNA molecules to other beads in 10x sequencing. In the script folder of TRUST4, we provide a script barcoderep-filter to alleviate the diffusion effects. You can simply run it as "python3 barcoderep-filter.py TRUST_barcode_report.tsv > newreport.tsv". This script is for the gene expression library of 10x data, so it does not have the feature to filter the cells with low TCR coverage.
