### ISSUE TITLE
Running TRUST4 separately on mapped and not aligned reads

### ISSUE THREAD

**Issue by Michael-Geuenich** [liulab-dfci/TRUST4#85]
For some technical reasons I have to run TRUST4 twice: once on bam files of all reads that aligned, and once on fastq files **of the same sample** containing only reads that did not align to the reference.

I only need the report.tsv file outputs from TRUST4, and I was wondering if I could just merge the two? Obviously I would need to re-calculate the frequency which is no problem, but I am wondering if there would be any other issues with this approach?

Part of the reason I am asking is because I found that the cid and cid_full_length columns do not match even though the CDR3nt column matches between two report files (one from aligned bam and one from the non-mapped fastq). But my understanding is that these columns link each sequence to the assembled scaffold, so they should not matter, is that correct?

Thank you for providing such a wonderful and well implemented tool!

**Comment by mourisl** [comment]
Yes, you can merge the identical CDR3s in the report files and recalculate their abundances and fractions. I don't think there is any big issue with this approach. 
Cid, cid_full_length does not matter the clonotype analysis, so you can ignore those two values. 

I think a better way is to combine those extracted candidate reads before the assembly starts, which might increase the sensitivity. Since you already run TRUST4 on these files, you can concatenate the "toassemble.fq" from two sources, and run TRUST4 on the concatenated file. You can set a convenient file name and run TRUST4 with option "--stage 1" so it can use the extracted candidate reads.

**Comment by Michael-Geuenich** [comment]
Oh, thank you for this suggestion! I've implemented this and it has worked great!
